<a href="https://colab.research.google.com/github/Azewkhan/Azewkhan/blob/main/Basics%20of%20Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'


In [4]:
print(tf.__version__)

2.15.0


In [19]:
#Initialising a Tensor

x= tf.ones((3,3))
x = tf.zeros((2,3))
x = tf.eye(3)
x = tf.random.normal((3,3), mean =0 , stddev=1)
x =tf.random.uniform((3,3),minval=0, maxval=10)
x= tf.range(start=1, limit =6,delta =3)
print(x)

tf.Tensor([1 4], shape=(2,), dtype=int32)


In [21]:
  # Initiation
   x=  tf.random.normal((2,3))
   y= tf.random.normal((3,4))

   x= tf.constant([1,2,3,4], shape= (2,2))
   y = tf.constant([9,8,7])

   z= tf.add(x,2)
   z= tf.subtract(x,2)
   z= tf.divide(x,2)
   z= tf.multiply(x,2)


   #z=  x @ y
   #print(z)

   #z = tf.matmul(x,y)
   print(z)

tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)


In [55]:
#Indexing

x = tf.constant([0,1,1,2,3,1,2,3])

#print(x[:])
#print(x[1:])
#print(x[:12])
#print(x[4::-1])

india = tf.constant([0,4])
x_india =tf.gather(x, india)
#print(x_india)

x = tf.constant([[1,2],[3,4],[5,6]])

#print(x)
print(x[0:2])



tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [61]:
#Reshaping

x = tf.range(9)
x = tf.reshape(x,(3,3))
x= tf.transpose(x, perm=[1,0])
print(x)



tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
