<a href="https://colab.research.google.com/github/Azewkhan/Azewkhan/blob/main/Tensor_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

A =tf.random.uniform(shape = (3,3), minval= -1, maxval= 1)
B =tf.random.uniform(shape = (3,3), minval= -1, maxval= 1)
C = tf.add(A,B)
D = tf.multiply(A,B)
E = tf.divide(A,B)
F = tf.subtract(A,B)


print("Tensor A")
print(A)
print('-'*20)
print("Tensor B")
print(B)
print('-'*20)
print("Addition of Tensor A and Tensor B")
print(C)
print('-'*20)
print("Multiplication of Tensor A and Tensor B")
print(D)
print('-'*20)
print("Division of Tensor A and Tensor B")
print(E)
print('-'*20)
print("Subtraction of Tensor A and Tensor B")
print(F)



Tensor A
tf.Tensor(
[[ 0.57000446  0.5653031  -0.08526301]
 [ 0.77348924  0.09369636 -0.91183496]
 [ 0.13755989 -0.6998575  -0.86638856]], shape=(3, 3), dtype=float32)
--------------------
Tensor B
tf.Tensor(
[[-0.19237328 -0.3603897   0.29609776]
 [ 0.13139105  0.8150058   0.81532216]
 [ 0.9104116  -0.09499311  0.5667095 ]], shape=(3, 3), dtype=float32)
--------------------
Addition of Tensor A and Tensor B
tf.Tensor(
[[ 0.3776312   0.20491338  0.21083474]
 [ 0.9048803   0.90870214 -0.09651279]
 [ 1.0479715  -0.7948506  -0.29967904]], shape=(3, 3), dtype=float32)
--------------------
Multiplication of Tensor A and Tensor B
tf.Tensor(
[[-0.10965363 -0.20372942 -0.02524619]
 [ 0.10162956  0.07636307 -0.74343926]
 [ 0.12523612  0.06648164 -0.49099064]], shape=(3, 3), dtype=float32)
--------------------
Division of Tensor A and Tensor B
tf.Tensor(
[[-2.9630127  -1.5685883  -0.2879556 ]
 [ 5.8869247   0.11496404 -1.1183739 ]
 [ 0.15109637  7.3674545  -1.5288054 ]], shape=(3, 3), dtype=floa

In [ ]:
import numpy as np

#Method 1
snow_tensor1 = tf.constant([[5, 6], [7, 8]],shape= (2,2), dtype='float32')
print(snow_tensor1)

#Method 2
snow = np.array([[5, 6], [7, 8]], dtype='float32')
snow_tensor2 = tf.convert_to_tensor(snow)

print(snow_tensor2)

tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [ ]:
from keras.utils import to_categorical

label = "santaclaus"
encoded_label = to_categorical([0], num_classes=len(label))

print("Encoded Tensor:")
print(encoded_label)
print("\nNumber of Dimensions:", encoded_label.ndim)

Encoded Tensor:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Number of Dimensions: 2


In [ ]:
from keras.models import Sequential
from keras.layers import Dense

# Sequential Model
model = Sequential()
model.add(Dense(128, input_shape=(784,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()




Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 128)               16512     
                                                                 
 dense_2 (Dense)             (None, 64)                8256      
                                                                 
 dense_3 (Dense)             (None, 1)                 65        
                                                                 
Total params: 125313 (489.50 KB)
Trainable params: 125313 (489.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

#Splitting the datasets into traininng and testing
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)

# Truncating the reviews which has more than 1000 words
x_train = np.array([np.pad(sequence, (0, max(0, 1000 - len(sequence))), 'constant')[:1000] for sequence in x_train])
x_test = np.array([np.pad(sequence, (0, max(0, 1000 - len(sequence))), 'constant')[:1000] for sequence in x_test])


model = Sequential()
model.add(Dense(128, input_shape=(1000,), activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy')

model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

# Evaluate the model
y_pred = model.predict(x_test)
y_pred = (y_pred_prob > 0.5).astype(int)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)


Epoch 1/10
625/625 [==============================] - 5s 5ms/step - loss: 34.6187 - val_loss: 3.5005
Epoch 2/10
625/625 [==============================] - 2s 4ms/step - loss: 3.0976 - val_loss: 2.6454
Epoch 3/10
625/625 [==============================] - 3s 4ms/step - loss: 2.1118 - val_loss: 1.5613
Epoch 4/10
625/625 [==============================] - 3s 4ms/step - loss: 1.3814 - val_loss: 1.5883
Epoch 5/10
625/625 [==============================] - 2s 4ms/step - loss: 1.1999 - val_loss: 1.7965
Epoch 6/10
625/625 [==============================] - 2s 3ms/step - loss: 1.1327 - val_loss: 1.5508
Epoch 7/10
625/625 [==============================] - 2s 3ms/step - loss: 0.9860 - val_loss: 1.2377
Epoch 8/10
625/625 [==============================] - 2s 3ms/step - loss: 0.9371 - val_loss: 1.2629
Epoch 9/10
625/625 [==============================] - 2s 3ms/step - loss: 1.0332 - val_loss: 1.7969
Epoch 10/10
782/782 [==============================] - 2s 2ms/step
Accuracy: 0.50956
Precision: 0.5

In [ ]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
import numpy as np

fashion_mnist = tf.keras.datasets.fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

print("Training set shape:", x_train.shape)
print("Training labels shape:", y_train.shape)
print("Test set shape:", x_test.shape)
print("Test labels shape:", y_test.shape)

x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, stratify=y_train, random_state=68)

# Inspect class distribution in training, validation, and testing sets
train_class_distribution = np.bincount(y_train)
val_class_distribution = np.bincount(y_val)
test_class_distribution = np.bincount(y_test)

print("-"*20)
print("Class Distribution in Training Set:")
for class_idx, count in enumerate(train_class_distribution):
    print(f"Class {class_idx}: {count} samples")

print("-"*20)
print("\nClass Distribution in Validation Set:")
for class_idx, count in enumerate(val_class_distribution):
    print(f"Class {class_idx}: {count} samples")

print("-"*20)
print("\nClass Distribution in Test Set:")
for class_idx, count in enumerate(test_class_distribution):
    print(f"Class {class_idx}: {count} samples")


Training set shape: (60000, 28, 28)
Training labels shape: (60000,)
Test set shape: (10000, 28, 28)
Test labels shape: (10000,)
--------------------
Class Distribution in Training Set:
Class 0: 4800 samples
Class 1: 4800 samples
Class 2: 4800 samples
Class 3: 4800 samples
Class 4: 4800 samples
Class 5: 4800 samples
Class 6: 4800 samples
Class 7: 4800 samples
Class 8: 4800 samples
Class 9: 4800 samples
--------------------

Class Distribution in Validation Set:
Class 0: 1200 samples
Class 1: 1200 samples
Class 2: 1200 samples
Class 3: 1200 samples
Class 4: 1200 samples
Class 5: 1200 samples
Class 6: 1200 samples
Class 7: 1200 samples
Class 8: 1200 samples
Class 9: 1200 samples
--------------------

Class Distribution in Test Set:
Class 0: 1000 samples
Class 1: 1000 samples
Class 2: 1000 samples
Class 3: 1000 samples
Class 4: 1000 samples
Class 5: 1000 samples
Class 6: 1000 samples
Class 7: 1000 samples
Class 8: 1000 samples
Class 9: 1000 samples


In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, callbacks


fashion_mnist = tf.keras.datasets.fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
x_train = x_train.reshape((-1, 28, 28, 1)) / 255.0
x_test = x_test.reshape((-1, 28, 28, 1)) / 255.0


# Model architecture
model = tf.keras.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
early_stopping = callbacks.EarlyStopping(monitor='val_loss', patience=3, verbose=1)

# Train the model with EarlyStopping callback
history = model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test), callbacks=[early_stopping])


Epoch 1/10
1875/1875 [==============================] - 22s 10ms/step - loss: 0.5137 - accuracy: 0.8118 - val_loss: 0.3832 - val_accuracy: 0.8630
Epoch 2/10
1875/1875 [==============================] - 20s 11ms/step - loss: 0.3305 - accuracy: 0.8788 - val_loss: 0.3225 - val_accuracy: 0.8841
Epoch 3/10
1875/1875 [==============================] - 18s 9ms/step - loss: 0.2827 - accuracy: 0.8952 - val_loss: 0.2998 - val_accuracy: 0.8915
Epoch 4/10
1875/1875 [==============================] - 16s 9ms/step - loss: 0.2512 - accuracy: 0.9081 - val_loss: 0.3051 - val_accuracy: 0.8906
Epoch 5/10
1875/1875 [==============================] - 21s 11ms/step - loss: 0.2296 - accuracy: 0.9149 - val_loss: 0.2692 - val_accuracy: 0.9029
Epoch 6/10
1875/1875 [==============================] - 18s 9ms/step - loss: 0.2063 - accuracy: 0.9234 - val_loss: 0.2642 - val_accuracy: 0.9053
Epoch 7/10
1875/1875 [==============================] - 18s 9ms/step - loss: 0.1905 - accuracy: 0.9288 - val_loss: 0.2664 - val

In [ ]:
import tensorflow as tf
import numpy as np

# Define a custom model class inheriting from tf.keras.Model
class CustomModel(tf.keras.Model):
    def __init__(self):
        super(CustomModel, self).__init__()
        self.dense1 = tf.keras.layers.Dense(64, activation='relu')
        self.dense2 = tf.keras.layers.Dense(32, activation='relu')
        self.dense3 = tf.keras.layers.Dense(1)
    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        return self.dense3(x)

# Create an instance of the custom model
model = CustomModel()

# Generate synthetic data for regression
np.random.seed(0)
X_train = np.random.rand(1000, 10)
y_train = np.random.rand(1000, 1)

model.compile(optimizer=tf.keras.optimizers.Adam(), loss=tf.keras.losses.MeanSquaredError())

model.fit(X_train, y_train, epochs=10, batch_size=32)


Epoch 1/10
32/32 [==============================] - 1s 3ms/step - loss: 0.0927
Epoch 2/10
32/32 [==============================] - 0s 3ms/step - loss: 0.0869
Epoch 3/10
32/32 [==============================] - 0s 3ms/step - loss: 0.0836
Epoch 4/10
32/32 [==============================] - 0s 2ms/step - loss: 0.0822
Epoch 5/10
32/32 [==============================] - 0s 2ms/step - loss: 0.0816
Epoch 6/10
32/32 [==============================] - 0s 2ms/step - loss: 0.0808
Epoch 7/10
32/32 [==============================] - 0s 3ms/step - loss: 0.0799
Epoch 8/10
32/32 [==============================] - 0s 2ms/step - loss: 0.0802
Epoch 9/10
32/32 [==============================] - 0s 2ms/step - loss: 0.0784
Epoch 10/10
32/32 [==============================] - 0s 2ms/step - loss: 0.0781


In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)

x_train = pad_sequences(x_train, maxlen= 1000, padding='post')
x_test = pad_sequences(x_test, maxlen= 1000, padding='post')


# Build the text classification model
model = Sequential([
    Embedding(input_dim= 10000 , output_dim= 50, input_length= 1000),
    Flatten(),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test, y_test))




Epoch 1/5
782/782 [==============================] - 30s 37ms/step - loss: 0.4246 - accuracy: 0.7937 - val_loss: 0.3026 - val_accuracy: 0.8743
Epoch 2/5
782/782 [==============================] - 30s 38ms/step - loss: 0.1523 - accuracy: 0.9466 - val_loss: 0.3437 - val_accuracy: 0.8653
Epoch 3/5
782/782 [==============================] - 31s 40ms/step - loss: 0.0293 - accuracy: 0.9939 - val_loss: 0.4213 - val_accuracy: 0.8635
Epoch 4/5
782/782 [==============================] - 29s 37ms/step - loss: 0.0039 - accuracy: 0.9997 - val_loss: 0.4956 - val_accuracy: 0.8635
Epoch 5/5
782/782 [==============================] - 31s 39ms/step - loss: 0.0010 - accuracy: 1.0000 - val_loss: 0.5477 - val_accuracy: 0.8619
